version: "3.8"

networks:
  elastic:
volumes:
  certs:
  es01_logs:
  es01_data:
  kibana_data:
  logstash_data:

services:
  setup:
    container_name: setup
    build:
      context: setup/
      args:
        STACK_VERSION: $STACK_VERSION
        ELASTIC_PASSWORD: $ELASTIC_PASSWORD
        KIBANA_PASSWORD: $KIBANA_PASSWORD
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - ./setup/instances.yml:/usr/share/elasticsearch/instances.yml
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 3

  es01:
    container_name: es01
    depends_on:
      setup:
        condition: service_healthy
    build:
      context: elasticsearch/
      args:
        STACK_VERSION: $STACK_VERSION
        ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - es01_data:/usr/share/elasticsearch/data
      - es01_logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    ports:
      - 9200:9200
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 8s
      retries: 5

  kibana:
    container_name: kibana
    depends_on:
      es01:
        condition: service_healthy
    build:
      context: kibana/
      args:
        STACK_VERSION: $STACK_VERSION
        KIBANA_PASSWORD: $KIBANA_PASSWORD
        ENCRYPTION_KEY: $ENCRYPTION_KEY
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibana_data:/usr/share/kibana/data
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic
    ports:
      - 5601:5601
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q 'HTTP/1.1 200'",
        ]
      interval: 10s
      timeout: 8s
      retries: 5

  logstash:
    container_name: logstash
    depends_on:
      - es01
    build:
      context: logstash/
      args:
        STACK_VERSION: $STACK_VERSION
        LOGSTASH_PASSWORD: $LOGSTASH_PASSWORD
    volumes:
      - certs:/usr/share/logstash/config/certs
      - logstash_data:/usr/share/logstash/data
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elastic
    #restart: unless-stopped

